name: Deploy to HF Space

on:
  push:
    branches: [ main ]
    paths:
      - 'langflow-space/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Sync to HF Space
        env:
          HF_SPACE: jcmtomorandd/langflow-dk
          HF_TOKEN: ${{ secrets.HF_TOKEN_FOR_GITHUB }}
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@users.noreply.github.com
        run: |
          set -eux
          # 1) HF Space を clone
          git clone https://huggingface.co/spaces/${HF_SPACE} hfrepo

          # 2) Git 管理フォルダを保護しつつ同期
          rsync -av --delete --exclude '.git' --exclude '.git/**' langflow-space/ hfrepo/

          # 3) hfrepo でコミット
          cd hfrepo
          git config user.email "${GIT_AUTHOR_EMAIL}"
          git config user.name "${GIT_AUTHOR_NAME}"
          git add -A
          git commit -m "Sync from GitHub" || echo "No changes to commit"

          # <確認ポイント> HF に置く Dockerfile の先頭を出力
          echo "----- HFrepo Dockerfile (head) -----"
          head -n 80 Dockerfile || true
          echo "-------------------------------------"

          # 4) 認証 URL に切替 → 取り込み → 強制 push
          git remote set-url origin https://${GITHUB_ACTOR}:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE}.git
          git pull --rebase origin main || true
          git push -f origin HEAD:main
